# Generated by Django 4.2.8 on 2023-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_location_name_location_city_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='more',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
