# Generated by Django 4.2.8 on 2023-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='more',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
