# Generated by Django 4.2.8 on 2023-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_location_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
